resolver: lts-18.13

packages:
  - .

extra-deps:
  - github: abarbu/dot
    commit: 6cdac3d452fd128b1e5b0aa13057cec505842cf9
  - github: waddlaw/haskell-stack-trace-plugin
    commit: c9ce1767377cf325569fb2be355431f1851f5fc9

allow-newer: true

nix:
  enable: false
  shell-file: shell.nix
